version: "3.7"

volumes:
  jenkins_volumes:
    driver: local

services:
  jenkins:
    image: jenkins_php:latest
    container_name: jenkins_php
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - jenkins_volumes:/var/jenkins_home
