name: Publish Docker image

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' #every sunday

env:
  TEST_TAG: janopl/jenkins-php:test

jobs:
  build:
    name: Build image
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: jenkins-php:latest
          outputs: type=docker,dest=/tmp/jenkins-php.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jenkins-php
          path: /tmp/jenkins-php.tar


  push_to_registry:
    if: github.event_name == 'pull_request'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: jenkins-php
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/jenkins-php.tar
          docker image ls -a

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}